### ISSUE TITLE
Issue with sample / TypeScript error

### ISSUE THREAD

**Issue by selvaag** [pnp/sp-dev-fx-extensions#207] opened 2019-02-19 18:44 UTC
## Category

- [x] Question
- [ ] Bug

## Expected or Desired Behavior

Error try compile

## Observed Behavior

I get error when compile:

[19:39:15] Error - [tsc] src/extensions/print/components/print-dialog-content/print-dialog-content.tsx(3,8): error TS1192: Module '"C:/Users/**/Documents/Development/SharePoint/SPFx/testing/react-command-print/node_modules/react-to-print/lib/index"' has no default export.
[19:39:15] Error - 'tsc' sub task errored after 5.2 s 
 exited with code 2

## Submission Guidelines

Appreciate feedback on how to resolve this issue. 

Thanks for your contribution! Sharing is caring.

**Comment by jcosta33** [comment] 2019-02-19 18:53
Duplicate of this?
https://github.com/Microsoft/TypeScript-React-Starter/issues/8

**Comment by selvaag** [comment] 2019-02-19 19:15
Looks same, but after changed code in file:  
(ref. file \src\extensions\print\components\print-dialog-content\print-dialog-content.tsx)

To: `import * as ReactToPrint from "react-to-print";` 

The initial error fixed but **After compile retry, I get another error:**

[20:07:00] Error - [tsc] src/extensions/print/components/print-dialog-content/print-dialog-content.tsx(95,33): error TS2322: Type '{ trigger: () => Element; content: () => any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactToPrint> & Readonly<{ children?: ReactNode; }...'.

**Comment by jcosta33** [comment] 2019-02-20 15:26
Looks like you're trying to assign a data structure that isn't compatible with the type typescript is infering or you're declaring. You can use type assertion to bypass this. 

https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html

But you shouldn't have to. You should get comfortable with typescript and the type system and understand it as best you can, it'll improve your code.

**Comment by hugoabernier** [comment] 2020-05-21 08:45
@selvaag did you ever resolve this issue with @jcosta33 's suggestion?

I'll go ahead and close it as there has been no activity here for a while. Feel free to open a new issue to the sp-dev-docs repository if you're still running into this problem, as this repository is for extension samples -- not general SharePoint development.

**Closed** 2020-05-21 08:45 UTC
